security:
    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12

    providers:
        default:
            entity: { class: AppBundle\Entity\Users }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern: .*
            form_login:
                login_path:     /login
                check_path:     /login_check
                default_target_path: _viewing_page
                csrf_provider: security.csrf.token_manager
                use_referer:    true
            logout:
                path:   /logout
                target: /
            remember_me:
                name:     "rcsh"
                key:      "knhr!oie4u2@3hfdi32ppmxfd"
                lifetime: 31536000
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            anonymous: ~
            